### ISSUE TITLE
Can't use pip install serverlessrepo anymore

### ISSUE THREAD

**Issue by sblask** [awslabs/aws-serverlessrepo-python#21]
```
$ pip install serverlessrepo
Collecting serverlessrepo
  Could not find a version that satisfies the requirement serverlessrepo (from versions: )
No matching distribution found for serverlessrepo
$ python --version
Python 3.5.2
```
First started to fail 2 days ago: https://travis-ci.org/sblask/dotfiles/builds
Seems to be a sudden incompatibility to Python 3.5 which is the standard Python in Ubuntu 16.04 (LTS)

**Comment by paoptu023** [comment]
Hi, I’m not sure why the build didn’t fail before, but we only support  Python 2.7 and 3.6 or greater: https://github.com/awslabs/aws-serverlessrepo-python/blob/master/setup.py#L50.

**Comment by sblask** [comment]
Was that introduced in the new release? Any particular reason for not supporting Python 3.5? I've been running aws-sam-cli for a couple of months with Python 3.5 without any problems so far...

**Comment by paoptu023** [comment]
I'll add python 3.5 into our supported versions, but I can't guarantee that it will solve your issue. Note that 3.5 is not a supported version for aws-sam-cli according to its [setup.py](https://github.com/awslabs/aws-sam-cli/blob/develop/setup.py#L48). The best solution would be using python 3.6 in your build, and everything will work seamlessly.

**Comment by sblask** [comment]
I have Python 3.5 in my Travis config to mirror my system Python. I could update to something more recent, but the point of using an LTS is not to have to.
I am not sure how Pypi works in this regard, but it seems like aws-sam-cli does not set the version info explicitly there. As least it's not on the description page like it is for serverlessrepo.

**Comment by jfuss** [comment]
@sblask We do have it set in our [setup.py](https://github.com/awslabs/aws-sam-cli/blob/develop/setup.py#L48) and have for some time now. SAM CLI has never supported anything but Python2.7, 3.6 and 3.7. https://github.com/awslabs/aws-sam-cli/pull/891 is aimed to fix this in PyPi. With that said, you should move off of Python3.5 and onto a directly supported version, ideally though one of our installers instead of using pip.

**Comment by sblask** [comment]
@jfuss fair enough, I just know that I can do `pip install aws-sam-cli` and run it under Python 3.5 without any problems so far. And I don't see a reason why it wouldn't given that you support 2.7. No idea why I am not able to do `pip install serverlessrepo`. Should it stop working, I might just run SAM under Python 2.7 until it's end of life. Anyway, what do you mean by one of your installers? The Linuxbrew thingy? Reading through https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html it seems like `pip` is still the preferred option?

**Comment by jfuss** [comment]
This was by accident that it worked and it should have failed just like the serverless app repo did. ‘pip’ didn’t like something with our setup.py which didn’t fail for whatever reason and allowed installation on non-supported versions. Pip was an old installation mechanism before we had installers. There are many problems we have encounter with pip and the reason why we built installers for the SAM CLI. While you can install and we have some documentation still pointing to pip, the recommendation has been to not pip install and use the installers we have (for Linux and mac is Linuxbrew and homebrew and msi for Windows). We are working on removing some of the references we still have to install using pip and update them to our installers. 

I highly discourage installing into Py2.7. We will be moving off Py2.7 support before it’s EOL. The good news is if you just migrate to the installers you don’t have to worry about this. So instead of downgrading and then have to upgrade, I recommend doing the upgrade now.

**Comment by sblask** [comment]
We drifted kind of far away from the original issue. In my opinion supporting only >= Python 3.6 is very restrictive for a tool/library at the moment, Python 3.6 being only 2 years old and a Ubuntu LTS with Python 3.5 still active. But whatever you decide I make it work for me. However, I am quite sure I won't use Linuxbrew in this case. I like to install tools on my machine in a similar way I would do at work and I don't think I would use / rely on Linuxbrew for scripting purposes or in a CI environment. Pip is standard in the Python world. I have not idea what kind of issues you had, but it works for many other tools and I never had any unsurmountable issues with it.

**Comment by paoptu023** [comment]
Closing the issue since no further actions are needed from serverlessrepo.
